name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Generate variables
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag dreamldx/santisfactorymap:${{ steps.vars.outputs.sha_short }}
        docker push dreamldx/santisfactorymap:${{ steps.vars.outputs.sha_short }}
